Repository Richajaishwal0/Trip_assistant, pull requests merged in 2025-09, with the labels that each got.

#165 fix: remove duplicate icon in client/index.html
  client/index.html
Labels: Level 1, OSCI-25, chore

#179 Fix sign-up API error to ensure proper user registration (Fixes #176)
  server/controllers/userController.js
Labels: bug, Level 2, OSCI-25

#191 Improve footer design for better UI consistency (Fixes #182)
  client/src/App.tsx
  client/src/components/footer_new.tsx
Labels: enhancement, Level 2, OSCI-25
