Repository Richajaishwal0/Trip_assistant, pull requests merged in 2025-08, with the labels that each got.

#86 Phone Number Validation Fix - Issue
  client/src/pages/Auth.tsx
  client/src/test-phone-validation.js
Labels: bug, GSSOC-25, Level 2

#96 Add-favicon
  client/index.html
Labels: good first issue, Level 1, OSCI-25

#124 add pull request template for contributions ✅
  .github/pull_request_template.md
Labels: bug, good first issue, GSSOC-25, Level 2

#136 Add Login and Signup buttons to hero section for Issue #98
  client/src/pages/home.tsx
Labels: enhancement, GSSOC-25, Level 1, OSCI-25

#138 ENVIRONMENT: Missing Environment Variables
  .gitignore
  PULL_REQUEST_TEMPLATE.md
  README.md
  client/src/components/ErrorBoundary.tsx
  client/src/components/ErrorState.tsx
  client/src/components/WeatherCard.tsx
  client/src/components/chatbot.tsx
  client/src/pages/FindFriends.tsx
  client/src/pages/PlaceDetails.tsx
  client/src/test-phone-validation.js
  client/src/utils/apiUtils.ts
  server/.env.sample
  server/ENV_SETUP.md
  server/config/db.js
  server/controllers/placeController.js
  server/controllers/userController.js
  server/middleware/auth.js
  server/middleware/security.js
  server/migrate-passwords.js
  server/package-lock.json
  server/package.json
  server/security-audit.js
  server/server.js
  server/setup-db.js
  server/setup-env.js
  server/setup_database.sql
  server/test-bcrypt.js
  server/utils/envValidator.js
Labels: bug, GSSOC-25, Level 2

#161 Removed unwanted space from navbar #130
  client/src/App.tsx
Labels: bug, GSSOC-25, Level 2, OSCI-25

#154 feat/contact-page
  client/src/pages/Contact.tsx
Labels: enhancement, Level 2, OSCI-25

#143 Add user management routes for finding, updating, and deleting users
  server/controllers/userController.js
  server/routes/userRoutes.js
Labels: enhancement, Level 2, OSCI-25

#142 Fix footer social links #139
  client/src/components/footer.tsx
Labels: enhancement, GSSOC-25, Level 2, OSCI-25

#177 Enhance API reliability by adding Joi-based validation (Fixes #173)
  server/middleware/validation.js
  server/package-lock.json
  server/package.json
  server/routes/entry-point.js
  server/routes/placeRoutes.js
  server/routes/propertyRoutes.js
  server/routes/user-activity-check.js
  server/routes/userRoutes.js
  server/validators/README.md
  server/validators/activityValidators.js
  server/validators/placeValidators.js
  server/validators/propertyValidators.js
  server/validators/userValidators.js
Labels: enhancement, Level 2, OSCI-25

#175 Remove react-leaflet-cluster to fix compatibility (Fixes #172)
  client/package-lock.json
  client/package.json
Labels: Level 1, OSCI-25, chore
